package primcipal;

import Back_end.Generator;
import Back_end.Production;
import Front_end.Grammar;
import Front_end.Midle_front;
import Front_end.Statment;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Cid
 */
public class Principal extends javax.swing.JFrame {

    public static Set<String> terminais;
    public static Set<String> nonterminais;
    public static Set<Production> productions;
    public static String start;
    public String[][] tabela;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTParsing = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTOutPut = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(776, 615, 615, 615));
        setMinimumSize(new java.awt.Dimension(776, 615));

        jSplitPane3.setDividerLocation(400);
        jSplitPane3.setDividerSize(4);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(550);
        jSplitPane1.setDividerSize(4);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Parsing BNF"));

        jTParsing.setColumns(20);
        jTParsing.setRows(5);
        jTParsing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTParsingMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTParsing);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Output"));

        jTOutPut.setColumns(20);
        jTOutPut.setRows(5);
        jTOutPut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTOutPutMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTOutPut);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        jSplitPane3.setLeftComponent(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Avaliar expressão"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        );

        jSplitPane3.setRightComponent(jPanel2);

        jMenu1.setText("File");

        jMenuItem6.setText("Abrir Gramatica");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("Front end");

        jMenuItem5.setText("Token");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem7.setText("Validar Gramatica");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("First/Follow");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Back end");

        jMenuItem1.setText("LR(0)");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("LR(1)");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("SLR(1)");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("LALR");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public int conta(Statment s) {
        int i = 0;
        while (s.definitions[i] != null) {
            i++;
        }
        return i;
    }

    private void convert_grammar() {
        Midle_front aux = new Midle_front();

        terminais = aux.terminais();
        nonterminais = aux.nonterminais();
        productions = new LinkedHashSet<>();

        Grammar grammar = Midle_front.grammar;
        String nonTerminal = "";
        Production production;
        int cont = 0;
        int pega = 0;
        Statment[] statments = grammar.statments;

        for (Statment statment : statments) {

            if (statment != null) {
                if (pega == 0) {
                    start = statment.nonTerminal.token;
                    pega++;
                }
                nonTerminal = statment.nonTerminal.token;
                int i = 0;
                cont = conta(statment);
                String[] definitions = new String[cont];
                while (statment.definitions[i] != null) {
                    definitions[i] = statment.definitions[i].token;
                    i++;
                }
                production = new Production(nonTerminal, definitions);
                productions.add(production);
            }
        }
    }


    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Midle_front aux = new Midle_front();
        if (Midle_front.grammar != null) {
            String first_follow = aux.processa_first_follow();
            jTOutPut.setText(jTOutPut.getText() + first_follow);
        } else {
            JOptionPane.showMessageDialog(null, "MENSAGEM: FAVOR ABRIR ARQUIVO", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // Definir arquivos de entrada  
        Midle_front aux = new Midle_front();
        Midle_front.inputString = aux.ler_arquio();
        jTParsing.setText("ENTRADA \n" + Midle_front.inputString + "\n");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Midle_front aux = new Midle_front();
        if (!Midle_front.inputString.equals("")) {
            String token = aux.processa_token();
            jTOutPut.setText(token);
        } else {
            JOptionPane.showMessageDialog(null, "MENSAGEM: FAVOR ABRIR ARQUIVO", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Midle_front aux = new Midle_front();
        if (Midle_front.tokens.length > 0) {
            String gramar = aux.processa_gramatica();
            jTOutPut.setText(jTOutPut.getText() + "\n\nGRAMATICA \n" + gramar);
        } else {
            JOptionPane.showMessageDialog(null, "MENSAGEM: FAVOR ABRIR ARQUIVO", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //LR(0)
        convert_grammar();
        Back_end.Grammar grammar = new Back_end.Grammar();
        grammar.nonterminals = nonterminais;
        grammar.terminals = terminais;
        grammar.productions = productions;
        grammar.start = start;

        Generator jlr = new Generator(grammar);
        try {
            jlr.computeFirstFollowNullable();
            jlr.generateLR0Table();
            String auxiliar = jlr.generateOutput();        
            jTParsing.setText(jTParsing.getText() + "\nPARSING LR(0))\n" + auxiliar);
            Midle_front aux = new Midle_front();
            jTParsing.setText(jTParsing.getText() + "\n\nTABELA LR(0)\n" + aux.gera_tabela(auxiliar));
        } catch (Back_end.Error e) {
            JOptionPane.showMessageDialog(null, "Erro ao executar a construção LR (0): " + e, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //LR(1)
        convert_grammar();
        Back_end.Grammar grammar = new Back_end.Grammar();
        grammar.nonterminals = nonterminais;
        grammar.terminals = terminais;
        grammar.productions = productions;
        grammar.start = start;
        Generator jlr = new Generator(grammar);
        try {
            jlr.computeFirstFollowNullable();
            jlr.generateLR1Table();
            String auxiliar = jlr.generateOutput();
            jTParsing.setText(jTParsing.getText() + "\n\nPARSING LR(1)\n" + auxiliar);
            Midle_front aux = new Midle_front();
            jTParsing.setText(jTParsing.getText() + "\n\nTABELA LR(1)\n" + aux.gera_tabela(auxiliar));
        } catch (Back_end.Error e) {
            JOptionPane.showMessageDialog(null, "Erro ao executar a construção LR (1): " + e, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //SLR
        convert_grammar();
        Back_end.Grammar grammar = new Back_end.Grammar();
        grammar.nonterminals = nonterminais;
        grammar.terminals = terminais;
        grammar.productions = productions;
        grammar.start = start;
        Generator jslr = new Generator(grammar);
        try {
            jslr.computeFirstFollowNullable();
            jslr.generateSLR1Table();
            String auxiliar = jslr.generateOutput();
            jTParsing.setText(jTParsing.getText() + "\nPARSING SLR(1))\n" + auxiliar);
            Midle_front aux = new Midle_front();
            jTParsing.setText(jTParsing.getText() + "\n\nTABELA SLR(1)\n" + aux.gera_tabela(auxiliar));
        } catch (Back_end.Error e) {
            JOptionPane.showMessageDialog(null, "Erro ao executar a construção SLR (1): " + e, "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        //LALR
        convert_grammar();
        Back_end.Grammar grammar = new Back_end.Grammar();
        grammar.nonterminals = nonterminais;
        grammar.terminals = terminais;
        grammar.productions = productions;
        grammar.start = start;
        Generator jlalr = new Generator(grammar);
        try {
            jlalr.computeFirstFollowNullable();
            jlalr.generateLALR1Table();
            String auxiliar = jlalr.generateOutput();
            jTParsing.setText(jTParsing.getText() + "\nPARSING LALR(1))\n" + auxiliar);
            Midle_front aux = new Midle_front();
            jTParsing.setText(jTParsing.getText() + "\n\nTABELA LASLR(1)\n" + aux.gera_tabela(auxiliar));
        } catch (Back_end.Error e) {
            JOptionPane.showMessageDialog(null, "Erro ao executar a construção LALR (1): " + e, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jTParsingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTParsingMouseClicked

        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            Object[] options = {"Confirmar", "Cancelar"};
            int choice = JOptionPane.showOptionDialog(null, "Deseja limpar ?", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
            if (choice == JOptionPane.YES_OPTION) {
                jTParsing.setText("");
            }
        }


    }//GEN-LAST:event_jTParsingMouseClicked

    private void jTOutPutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTOutPutMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            Object[] options = {"Confirmar", "Cancelar"};
            int choice = JOptionPane.showOptionDialog(null, "Deseja limpar ?", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
            if (choice == JOptionPane.YES_OPTION) {
                jTOutPut.setText("");
            }
        }    }//GEN-LAST:event_jTOutPutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTextArea jTOutPut;
    private javax.swing.JTextArea jTParsing;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
